site_name: file-whisperer
repo_url: https://github.com/zeeshansayyed/file-whisperer
site_url: https://zeeshansayyed.github.io/file-whisperer
site_description: This application will help you organize  and your local computer.
site_author: Zeeshan Ali Sayyed
edit_uri: edit/main/docs/
repo_name: zeeshansayyed/file-whisperer
copyright: Maintained by <a href="https://zeeshansayyed.com">zeeshansayyed</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/file_whisperer"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zeeshansayyed/file-whisperer
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/file-whisperer

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
